/// Bilingual copy ported from the prototype `data.jsx` (STR).
///
/// Source of truth is `i18n/strings.i69n.json` (en) + `i18n/strings_ar.i69n.json`
/// (ar) — typed classes generated by i69n via build_runner (same setup as
/// core's localization). This file is only the lookup bridge so the ~300
/// existing `s.t('key')` call sites keep working; new code may use the typed
/// getters directly (`Strings().nudge_handle`).
///
/// Regenerate after editing the JSON: `dart run build_runner build` (in app/).
library;

import 'i18n/strings.i69n.dart';
import 'i18n/strings_ar.i69n.dart';

/// Compiled bundles. `Strings_ar` extends `Strings`, so any key missing from
/// Arabic falls back to English at the class level.
const _bundles = <String, Strings>{
  'en': Strings(),
  'ar': Strings_ar(),
};

/// Legacy keys that collide with Dart keywords — remapped during codegen
/// (same sanitization core applied to `common.continue`).
const _alias = <String, String>{
  'continue': 'continue_',
};

/// Translate [key] for [lang], falling back to English then the key itself.
String tr(String key, String lang) {
  final bundle = _bundles[lang] ?? _bundles['en']!;
  try {
    final value = bundle[_alias[key] ?? key];
    if (value is String) return value;
  } catch (_) {
    // nothrow flag returns the key path for unknown keys; treat as miss.
  }
  return key;
}
