/// Bilingual copy ported verbatim from the prototype `data.jsx` (STR).
/// Access via `tr(key, lang)`.
const Map<String, Map<String, String>> kStrings = {
  // Welcome
  'w_title': {'en': 'Your health, kept close.', 'ar': 'صحتك، دائماً قريبة.'},
  'w_sub': {
    'en': "Daily check-ins, medication reminders, and trends — saved on your phone, synced when you're ready.",
    'ar': 'متابعة يومية، تذكير بالدواء، ورسوم بيانية — محفوظة على هاتفك، وتُزامَن عند رغبتك.'
  },
  'w_start': {'en': 'Get started', 'ar': 'ابدأ الآن'},
  'w_have': {'en': 'I already have an account', 'ar': 'لديّ حساب بالفعل'},
  'w_signin': {'en': 'Sign in', 'ar': 'تسجيل الدخول'},
  'w_or': {'en': 'or', 'ar': 'أو'},
  'w_apple': {'en': 'Continue with Apple', 'ar': 'المتابعة مع Apple'},
  'w_google': {'en': 'Continue with Google', 'ar': 'المتابعة مع Google'},

  // Auth contact
  'em_title': {'en': "What's your email?", 'ar': 'ما هو بريدك الإلكتروني؟'},
  'em_help': {'en': "We'll send you a code to verify it's you.", 'ar': 'سنرسل لك رمزاً للتحقق من هويتك.'},
  'em_label': {'en': 'Email address', 'ar': 'البريد الإلكتروني'},
  'em_ph': {'en': 'you@example.com', 'ar': 'you@example.com'},
  'use_phone': {'en': 'Use phone instead', 'ar': 'استخدم رقم الهاتف'},
  'use_email': {'en': 'Use email instead', 'ar': 'استخدم البريد الإلكتروني'},
  'trust_private': {'en': 'Private by default', 'ar': 'خصوصية افتراضية'},
  'trust_offline': {'en': 'Works offline', 'ar': 'يعمل دون إنترنت'},
  'trust_device': {'en': 'Yours, always', 'ar': 'ملكك دائماً'},
  'em_otp_h': {'en': 'We sent a 6-digit code to', 'ar': 'أرسلنا رمزاً من 6 أرقام إلى'},

  // Handle / username
  'un_label': {'en': 'Handle', 'ar': 'المعرّف'},
  'un_ph': {'en': 'e.g. layla_hassan', 'ar': 'مثال: layla_hassan'},
  'un_avail': {'en': 'Available', 'ar': 'متاح'},
  'un_taken': {'en': 'Already taken', 'ar': 'مأخوذ بالفعل'},
  'un_checking': {'en': 'Checking…', 'ar': 'جارٍ التحقق…'},
  'un_invalid': {'en': 'Only letters, numbers, and _ (3–20 chars)', 'ar': 'أحرف وأرقام و_ فقط (3–20 حرفاً)'},

  // Phone
  'ph_title': {'en': "What's your number?", 'ar': 'ما رقم هاتفك؟'},
  'ph_help': {'en': "We'll text you a code to confirm it's you.", 'ar': 'سنرسل لك رمزاً عبر رسالة للتأكد من هويتك.'},
  'ph_label': {'en': 'Mobile number', 'ar': 'رقم الموبايل'},
  'ph_terms': {'en': "By continuing you agree to Balsm's terms and privacy policy.", 'ar': 'بالمتابعة فإنك توافق على شروط بَلسَم وسياسة الخصوصية.'},
  'continue': {'en': 'Continue', 'ar': 'متابعة'},

  // OTP
  'otp_title': {'en': 'Enter your code', 'ar': 'أدخل رمز التحقق'},
  'otp_help': {'en': 'We sent a 6-digit code to', 'ar': 'أرسلنا رمزاً من 6 أرقام إلى'},
  'otp_resend': {'en': 'Resend code', 'ar': 'إعادة إرسال الرمز'},
  'otp_in': {'en': 'Resend in', 'ar': 'إعادة الإرسال خلال'},
  'otp_wrong': {'en': 'Wrong number?', 'ar': 'الرقم غير صحيح؟'},
  'verify': {'en': 'Verify', 'ar': 'تأكيد'},

  // Profile setup
  'pf_title': {'en': 'Tell us about you', 'ar': 'عرّفنا بنفسك'},
  'pf_help': {'en': 'This helps your care team read your reports correctly.', 'ar': 'هذا يساعد فريق الرعاية على قراءة تقاريرك بدقة.'},
  'pf_fname': {'en': 'First name', 'ar': 'الاسم الأول'},
  'pf_lname': {'en': 'Last name', 'ar': 'اسم العائلة'},
  'pf_fname_ph': {'en': 'e.g. Layla', 'ar': 'مثال: ليلى'},
  'pf_lname_ph': {'en': 'e.g. Hassan', 'ar': 'مثال: حسن'},
  'pf_dob': {'en': 'Date of birth', 'ar': 'تاريخ الميلاد'},
  'pf_gender': {'en': 'Gender', 'ar': 'النوع'},
  'pf_female': {'en': 'Female', 'ar': 'أنثى'},
  'pf_male': {'en': 'Male', 'ar': 'ذكر'},
  'pf_gov': {'en': 'Governorate', 'ar': 'المحافظة'},
  'pf_create': {'en': 'Create my profile', 'ar': 'إنشاء ملفّي'},
  'pf_secure': {'en': 'Your details stay on this device.', 'ar': 'تبقى بياناتك على هذا الجهاز.'},

  // Home
  'greet': {'en': 'Good morning', 'ar': 'صباح الخير'},
  'today_lbl': {'en': "Today's check-in", 'ar': 'متابعة اليوم'},
  'hero_q': {'en': 'How are you feeling today?', 'ar': 'كيف تشعرين اليوم؟'},
  'hero_cta': {'en': 'Start check-in', 'ar': 'ابدأ المتابعة'},
  'hero_time': {'en': 'About 2 minutes', 'ar': 'حوالي دقيقتين'},
  'done_lbl': {'en': 'All done for today', 'ar': 'انتهيتِ لليوم'},
  'done_q': {'en': 'Check-in complete', 'ar': 'اكتملت المتابعة'},
  'streak': {'en': 'day streak', 'ar': 'يوم متتالٍ'},
  'streak_help': {'en': 'Checked in 6 of the last 7 days', 'ar': 'تابعتِ 6 من آخر 7 أيام'},
  'latest': {'en': 'Latest readings', 'ar': 'آخر القياسات'},
  'meds_today': {'en': "Today's medications", 'ar': 'أدوية اليوم'},
  'recent': {'en': 'Recent reports', 'ar': 'آخر التقارير'},
  'see_all': {'en': 'See all', 'ar': 'عرض الكل'},
  'taken': {'en': 'Taken', 'ar': 'مأخوذ'},
  'due': {'en': 'Due', 'ar': 'مستحق'},
  'take': {'en': 'Take', 'ar': 'أخذ'},

  // metrics
  'm_bp': {'en': 'Blood pressure', 'ar': 'ضغط الدم'},
  'm_glucose': {'en': 'Blood glucose', 'ar': 'سكر الدم'},
  'm_mood': {'en': 'Mood', 'ar': 'الحالة'},
  'm_pain': {'en': 'Pain', 'ar': 'الألم'},
  'm_weight': {'en': 'Weight', 'ar': 'الوزن'},
  'unit_bp': {'en': 'mmHg', 'ar': 'ملم زئبق'},
  'unit_glu': {'en': 'mg/dL', 'ar': 'مجم/دل'},
  'bp_normal': {'en': 'In range', 'ar': 'ضمن المعدل'},
  'bp_high': {'en': 'A little high', 'ar': 'أعلى قليلاً'},
  'yesterday': {'en': 'vs yesterday', 'ar': 'عن أمس'},

  // Report flow
  'step_of': {'en': 'of', 'ar': 'من'},
  'back': {'en': 'Back', 'ar': 'رجوع'},
  'finish': {'en': 'Finish check-in', 'ar': 'إنهاء المتابعة'},
  'skip_q': {'en': "I didn't measure this today", 'ar': 'لم أقِس هذا اليوم'},
  'q_mood_t': {'en': 'How are you feeling today?', 'ar': 'كيف تشعرين اليوم؟'},
  'q_mood_h': {'en': 'Pick the face that fits best.', 'ar': 'اختاري الوجه الأقرب لحالتك.'},
  'mood_1': {'en': 'Rough', 'ar': 'متعبة'},
  'mood_2': {'en': 'Low', 'ar': 'ضعيفة'},
  'mood_3': {'en': 'Okay', 'ar': 'عادية'},
  'mood_4': {'en': 'Good', 'ar': 'جيدة'},
  'mood_5': {'en': 'Great', 'ar': 'ممتازة'},
  'q_bp_t': {'en': "What's your blood pressure?", 'ar': 'كم ضغط دمك؟'},
  'q_bp_h': {'en': 'Tap a number, then use the keypad.', 'ar': 'اضغطي على الرقم ثم استخدمي لوحة الأرقام.'},
  'sys': {'en': 'Systolic', 'ar': 'الانقباضي'},
  'dia': {'en': 'Diastolic', 'ar': 'الانبساطي'},
  'q_glu_t': {'en': 'And your blood sugar?', 'ar': 'وكم نسبة السكر؟'},
  'q_glu_h': {'en': 'Enter the reading from your glucometer.', 'ar': 'أدخلي القراءة من جهاز قياس السكر.'},
  'glu_fast': {'en': 'Fasting', 'ar': 'صائمة'},
  'glu_meal': {'en': 'After a meal', 'ar': 'بعد الأكل'},
  'glu_random': {'en': 'Random', 'ar': 'عشوائي'},
  'q_med_t': {'en': 'Did you take your medications?', 'ar': 'هل أخذتِ أدويتك؟'},
  'q_med_h': {'en': "Tap each one you've taken today.", 'ar': 'اضغطي على كل دواء أخذتِه اليوم.'},
  'skipped': {'en': 'Skipped', 'ar': 'لم يُؤخذ'},
  'mark_skip': {'en': "Didn't take", 'ar': 'لم آخذه'},
  'q_sym_t': {'en': 'Any pain or symptoms?', 'ar': 'هل لديك ألم أو أعراض؟'},
  'q_sym_h': {'en': 'Slide to your pain level, then tap anything you feel.', 'ar': 'حرّكي المؤشر لمستوى الألم، ثم اختاري ما تشعرين به.'},
  'pain_0': {'en': 'No pain', 'ar': 'لا ألم'},
  'pain_mild': {'en': 'Mild', 'ar': 'خفيف'},
  'pain_mod': {'en': 'Moderate', 'ar': 'متوسط'},
  'pain_sev': {'en': 'Severe', 'ar': 'شديد'},
  'pain_worst': {'en': 'Worst', 'ar': 'الأسوأ'},
  'note_lbl': {'en': 'Anything else? (optional)', 'ar': 'أي شيء آخر؟ (اختياري)'},
  'note_ph': {'en': 'Add a note for your doctor…', 'ar': 'اكتبي ملاحظة لطبيبك…'},
  'add_photo': {'en': 'Add a photo', 'ar': 'إضافة صورة'},

  // symptoms
  's_headache': {'en': 'Headache', 'ar': 'صداع'},
  's_dizzy': {'en': 'Dizziness', 'ar': 'دوخة'},
  's_fatigue': {'en': 'Fatigue', 'ar': 'إرهاق'},
  's_blurred': {'en': 'Blurred vision', 'ar': 'تشوش الرؤية'},
  's_swelling': {'en': 'Swelling', 'ar': 'تورّم'},
  's_chest': {'en': 'Chest tightness', 'ar': 'ضيق بالصدر'},
  's_nausea': {'en': 'Nausea', 'ar': 'غثيان'},
  's_thirst': {'en': 'Excess thirst', 'ar': 'عطش زائد'},
  's_none': {'en': 'Nothing', 'ar': 'لا شيء'},

  // Summary
  'saved_t': {'en': 'Check-in saved', 'ar': 'تم حفظ المتابعة'},
  'saved_local': {'en': 'Saved locally. Will sync when you reconnect.', 'ar': 'حُفظ محلياً — ستتم المزامنة عند الاتصال.'},
  'to_doctor': {'en': 'A copy reaches Dr. Sara at your next visit.', 'ar': 'ستصل نسخة إلى د. سارة في زيارتك القادمة.'},
  'meds_taken': {'en': 'taken', 'ar': 'مأخوذة'},
  'to_home': {'en': 'Back to home', 'ar': 'العودة للرئيسية'},
  'view_trends': {'en': 'View trends', 'ar': 'عرض الرسوم'},
  'no_symptoms': {'en': 'No symptoms', 'ar': 'لا أعراض'},

  // Trends / history
  'trends': {'en': 'Trends', 'ar': 'الرسوم البيانية'},
  'reports': {'en': 'Past reports', 'ar': 'التقارير السابقة'},
  'range_w': {'en': 'Week', 'ar': 'أسبوع'},
  'range_m': {'en': 'Month', 'ar': 'شهر'},
  'range_3m': {'en': '3 months', 'ar': '3 أشهر'},
  'avg': {'en': 'avg', 'ar': 'متوسط'},

  // Meds
  'medications': {'en': 'Medications', 'ar': 'الأدوية'},
  'morning': {'en': 'Morning', 'ar': 'الصباح'},
  'evening': {'en': 'Evening', 'ar': 'المساء'},
  'adherence': {'en': 'this week', 'ar': 'هذا الأسبوع'},
  'on_track': {'en': 'On track', 'ar': 'ملتزمة'},

  // Profile
  'profile': {'en': 'Profile', 'ar': 'الملف الشخصي'},
  'since': {'en': 'Balsm patient since', 'ar': 'مريضة بَلسَم منذ'},
  'p_personal': {'en': 'Account details', 'ar': 'تفاصيل الحساب'},
  'pd_account': {'en': 'Account', 'ar': 'الحساب'},
  'pd_share_qr': {'en': 'Share my QR code', 'ar': 'شارك رمز QR الخاص بي'},
  'pd_share_qr_h': {'en': 'Let others scan to connect', 'ar': 'ليتمكن الآخرون من المسح والتواصل'},
  'pd_qr_scan': {'en': 'Scan to connect on Balsm', 'ar': 'امسح للتواصل عبر بَلسَم'},
  'pd_nationality': {'en': 'Nationality', 'ar': 'الجنسية'},
  'nat_egyptian': {'en': 'Egyptian', 'ar': 'مصري'},
  'pd_blood': {'en': 'Blood type', 'ar': 'فصيلة الدم'},
  'pd_weight': {'en': 'Weight', 'ar': 'الوزن'},
  'pd_height': {'en': 'Height', 'ar': 'الطول'},
  'pd_phone': {'en': 'Mobile number', 'ar': 'رقم الهاتف'},
  'pd_nid': {'en': 'National ID', 'ar': 'الرقم القومي'},
  'pd_emergency': {'en': 'Emergency contact', 'ar': 'جهة اتصال الطوارئ'},
  'pd_em_name': {'en': 'Name', 'ar': 'الاسم'},
  'pd_em_rel': {'en': 'Relationship', 'ar': 'صلة القرابة'},
  'pd_em_phone': {'en': 'Phone', 'ar': 'الهاتف'},
  'pd_save': {'en': 'Save changes', 'ar': 'حفظ التغييرات'},
  'pd_saved': {'en': 'Saved', 'ar': 'تم الحفظ'},
  'conn_accounts': {'en': 'Connected accounts', 'ar': 'الحسابات المرتبطة'},
  'conn_apple': {'en': 'Apple ID', 'ar': 'Apple ID'},
  'conn_google': {'en': 'Google account', 'ar': 'حساب Google'},
  'conn_connect': {'en': 'Connect', 'ar': 'ربط'},
  'conn_remove': {'en': 'Remove', 'ar': 'إلغاء الربط'},
  'store_backup_to': {'en': 'Back up to', 'ar': 'نسخ إلى'},
  'store_move_to': {'en': 'Move to', 'ar': 'نقل إلى'},
  'store_remove_cloud': {'en': 'Remove from cloud', 'ar': 'حذف من السحابة'},
  'store_remove_dev': {'en': 'Remove from device', 'ar': 'حذف من الجهاز'},
  'store_delete_all': {'en': 'Delete everywhere', 'ar': 'حذف من كل مكان'},
  'store_delete_rec': {'en': 'Delete record', 'ar': 'حذف السجل'},
  'p_cond': {'en': 'Medical profile', 'ar': 'الملف الطبي'},
  'p_care': {'en': 'Care team', 'ar': 'فريق الرعاية'},
  'p_notif': {'en': 'Reminders', 'ar': 'التذكيرات'},
  'p_lang': {'en': 'Language', 'ar': 'اللغة'},
  'p_privacy': {'en': 'Privacy & data', 'ar': 'الخصوصية والبيانات'},
  'p_help': {'en': 'Help & support', 'ar': 'المساعدة والدعم'},
  'p_signout': {'en': 'Sign out', 'ar': 'تسجيل الخروج'},
  'p_emergency': {'en': 'Emergency', 'ar': 'الطوارئ'},

  // Medical profile
  'pd_kg': {'en': 'kg', 'ar': 'كجم'},
  'pd_cm': {'en': 'cm', 'ar': 'سم'},
  'pd_conditions': {'en': 'Chronic conditions', 'ar': 'الحالات المزمنة'},
  'pd_allergies': {'en': 'Allergies', 'ar': 'الحساسية'},
  'pd_measurements': {'en': 'Measurements', 'ar': 'القياسات'},
  'pd_add_cond': {'en': 'Add a condition…', 'ar': 'أضف حالة…'},
  'pd_add_alg': {'en': 'Add an allergy…', 'ar': 'أضف حساسية…'},
  'bmi_label': {'en': 'BMI', 'ar': 'كتلة الجسم'},
  'bmi_under': {'en': 'Underweight', 'ar': 'نقص وزن'},
  'bmi_normal': {'en': 'Healthy', 'ar': 'صحي'},
  'bmi_over': {'en': 'Overweight', 'ar': 'زيادة وزن'},
  'bmi_obese': {'en': 'Obese', 'ar': 'سمنة'},

  // Care team
  'care_intro': {'en': 'The doctors following your condition and who can see your reports.', 'ar': 'الأطباء الذين يتابعون حالتك ويرون تقاريرك.'},
  'care_primary': {'en': 'Primary', 'ar': 'الطبيب الأساسي'},
  'care_message': {'en': 'Message', 'ar': 'رسالة'},
  'care_book': {'en': 'Book', 'ar': 'حجز'},
  'care_find': {'en': 'Find a new doctor', 'ar': 'ابحث عن طبيب جديد'},

  // Privacy & data
  'pv_sharing': {'en': 'Data sharing', 'ar': 'مشاركة البيانات'},
  'pv_share_team': {'en': 'Share reports with care team', 'ar': 'مشاركة التقارير مع فريق الرعاية'},
  'pv_share_team_h': {'en': 'Your doctors can see your daily readings', 'ar': 'يرى أطباؤك قراءاتك اليومية'},
  'pv_analytics': {'en': 'Anonymous analytics', 'ar': 'تحليلات مجهولة'},
  'pv_analytics_h': {'en': 'Help us improve the app', 'ar': 'ساعدنا على تحسين التطبيق'},
  'pv_research': {'en': 'Research contributions', 'ar': 'المساهمة في الأبحاث'},
  'pv_research_h': {'en': 'De-identified data for medical studies', 'ar': 'بيانات مجهولة للأبحاث الطبية'},
  'pv_security': {'en': 'Security', 'ar': 'الأمان'},
  'pv_bio': {'en': 'Biometric app lock', 'ar': 'قفل بالبصمة / الوجه'},
  'pv_bio_h': {'en': 'Unlock with Face ID / fingerprint', 'ar': 'افتح التطبيق ببصمتك'},
  'pv_pin': {'en': 'Require PIN on open', 'ar': 'طلب رمز PIN عند الفتح'},
  'pv_pin_h': {'en': 'An extra layer of protection', 'ar': 'طبقة حماية إضافية'},
  'pv_yourdata': {'en': 'Your data', 'ar': 'بياناتك'},
  'pv_export': {'en': 'Export my data', 'ar': 'تصدير بياناتي'},
  'pv_export_h': {'en': 'As a PDF or CSV file', 'ar': 'ملف PDF أو CSV'},
  'pv_download': {'en': 'Download health records', 'ar': 'تحميل السجلات الصحية'},
  'pv_download_h': {'en': 'All labs and scans', 'ar': 'جميع التحاليل والأشعة'},
  'pv_connected': {'en': 'Connected apps', 'ar': 'التطبيقات المتصلة'},
  'pv_connected_h': {'en': 'Manage third-party access', 'ar': 'إدارة الوصول للطرف الثالث'},
  'pv_danger': {'en': 'Danger zone', 'ar': 'منطقة الخطر'},
  'pv_delete': {'en': 'Delete my account', 'ar': 'حذف حسابي'},
  'pv_delete_h': {'en': 'Permanently erase all your data', 'ar': 'حذف دائم لكل بياناتك'},
  'pv_encrypted': {'en': 'Your data is encrypted and protected', 'ar': 'بياناتك مشفّرة ومحمية'},

  // Emergency
  'em_eg': {'en': 'Egypt', 'ar': 'مصر'},
  'em_intro': {'en': "Egypt's nationwide emergency lines. Tap any number to call right away.", 'ar': 'خطوط الطوارئ على مستوى مصر. اضغط أي رقم للاتصال فوراً.'},
  'em_tap_call': {'en': 'Tap to call', 'ar': 'اضغط للاتصال'},
  'em_ambulance': {'en': 'Ambulance', 'ar': 'إسعاف'},
  'em_police': {'en': 'Police', 'ar': 'شرطة'},
  'em_fire': {'en': 'Fire & rescue', 'ar': 'الإطفاء والإنقاذ'},
  'em_tourist': {'en': 'Tourist police', 'ar': 'شرطة السياحة'},

  // Records (search + tags + dates)
  'rec_search_ph': {'en': 'Search records, tags, results…', 'ar': 'ابحث في السجلات والوسوم والنتائج…'},
  'rec_search_clear': {'en': 'Clear search', 'ar': 'مسح البحث'},
  'rec_tags': {'en': 'Tags', 'ar': 'الوسوم'},
  'rec_tags_ph': {'en': 'Add a tag and press Enter', 'ar': 'أضف وسماً واضغط Enter'},
  'rec_date': {'en': 'Date', 'ar': 'التاريخ'},
  'rec_no_results': {'en': 'No matching records', 'ar': 'لا سجلات مطابقة'},
  'rec_no_results_h': {'en': 'No records match', 'ar': 'لا سجلات تطابق'},
  'rec_no_results_h2': {'en': 'Nothing in this category yet.', 'ar': 'لا شيء في هذه الفئة بعد.'},
  'rec_clear_filters': {'en': 'Clear filters', 'ar': 'مسح عوامل التصفية'},

  // tabs
  'tab_home': {'en': 'Home', 'ar': 'الرئيسية'},
  'tab_map': {'en': 'Nearby', 'ar': 'قريب منك'},
  'tab_meds': {'en': 'Meds', 'ar': 'الأدوية'},
  'tab_profile': {'en': 'Profile', 'ar': 'الملف'},

  // Appointments
  'appts': {'en': 'Appointments', 'ar': 'المواعيد'},
  'upcoming_appt': {'en': 'Upcoming appointment', 'ar': 'الموعد القادم'},
  'past_appts': {'en': 'Past visits', 'ar': 'الزيارات السابقة'},
  'book_appt': {'en': 'Book', 'ar': 'حجز'},
  'no_appts': {'en': 'No upcoming appointments', 'ar': 'لا مواعيد قادمة'},
  'follow_up': {'en': 'Follow-up', 'ar': 'متابعة'},
  'check_up': {'en': 'Check-up', 'ar': 'فحص دوري'},
  'experience': {'en': 'experience', 'ar': 'خبرة'},
  'book_via_doctor': {'en': 'Your care team will schedule appointments for you.', 'ar': 'سيقوم فريق رعايتك بجدولة المواعيد لك.'},

  // Quick log
  'symptoms': {'en': 'Symptoms', 'ar': 'الأعراض'},
  'ql_title': {'en': "Let's check in", 'ar': 'لنسجّل متابعتك'},
  'ql_add_records': {'en': 'add to records', 'ar': 'أضف إلى السجلات'},
  'full_checkin': {'en': 'Full check-in', 'ar': 'المتابعة الكاملة'},
  'quick_log_or': {'en': 'or log just one', 'ar': 'أو سجّل قراءة واحدة'},
  'body_location': {'en': 'Where does it hurt?', 'ar': 'أين يؤلمك؟'},
  'your_accounts': {'en': 'Your accounts', 'ar': 'حساباتك'},
  'switch_account': {'en': 'Switch account', 'ar': 'تبديل الحساب'},
  'add_member': {'en': 'Add family member', 'ar': 'إضافة فرد من الأسرة'},

  // Prescriptions
  'prescriptions': {'en': 'Prescriptions', 'ar': 'الوصفات الطبية'},
  'rx_active': {'en': 'Active', 'ar': 'فعّالة'},
  'rx_expired': {'en': 'Expired', 'ar': 'منتهية'},
  'rx_valid_until': {'en': 'Valid until', 'ar': 'صالحة حتى'},
  'rx_show': {'en': 'Show to pharmacist', 'ar': 'أظهر للصيدلاني'},
  'rx_scan': {'en': 'Scan to dispense', 'ar': 'امسح للصرف'},

  // Settings: language & country
  'p_country': {'en': 'Country', 'ar': 'الدولة'},
  'choose_lang': {'en': 'Choose language', 'ar': 'اختر اللغة'},
  'choose_country': {'en': 'Where are you now?', 'ar': 'أين أنت الآن؟'},
  'travel_help': {'en': 'Set your location so Balsm shows local emergency numbers and care info while you travel.', 'ar': 'حدّد موقعك ليعرض بَلسَم أرقام الطوارئ ومعلومات الرعاية المحلية أثناء سفرك.'},
  'lang_full': {'en': 'Full support', 'ar': 'دعم كامل'},
  'lang_beta': {'en': 'Beta', 'ar': 'تجريبي'},
  'home_country': {'en': 'Home', 'ar': 'بلدك'},
  'away_banner': {'en': "You're away from home", 'ar': 'أنت خارج بلدك'},
  'emergency': {'en': 'Emergency', 'ar': 'الطوارئ'},

  // Health records
  'records': {'en': 'Health records', 'ar': 'السجلات الصحية'},
  'records_short': {'en': 'Records', 'ar': 'السجلات'},
  'add_record': {'en': 'Add record', 'ar': 'إضافة سجل'},
  'all_records': {'en': 'All', 'ar': 'الكل'},
  'rec_lab': {'en': 'Lab tests', 'ar': 'تحاليل'},
  'rec_scan': {'en': 'Scans', 'ar': 'أشعة'},
  'rec_report': {'en': 'Reports', 'ar': 'تقارير'},
  'rec_lab_one': {'en': 'Lab test', 'ar': 'تحليل'},
  'rec_scan_one': {'en': 'Scan', 'ar': 'أشعة'},
  'rec_report_one': {'en': 'Report', 'ar': 'تقرير'},
  'rec_self': {'en': 'You uploaded', 'ar': 'رفعتَه بنفسك'},
  'rec_empty': {'en': 'No records yet', 'ar': 'لا توجد سجلات بعد'},
  'rec_source': {'en': 'Source', 'ar': 'المصدر'},
  'rec_view': {'en': 'View document', 'ar': 'عرض المستند'},
  'rec_share': {'en': 'Share with doctor', 'ar': 'مشاركة مع الطبيب'},
  'rec_empty_h': {'en': 'Add a lab test, scan, or report to keep your whole history in one place.', 'ar': 'أضف تحليلاً أو أشعة أو تقريراً لتحتفظ بتاريخك كاملاً في مكان واحد.'},
  'rec_pick_type': {'en': 'What are you adding?', 'ar': 'ما الذي تضيفه؟'},
  'rec_title': {'en': 'Title', 'ar': 'العنوان'},
  'rec_title_ph': {'en': 'e.g. HbA1c blood test', 'ar': 'مثال: تحليل السكر التراكمي'},
  'rec_attach': {'en': 'Attach file or photo', 'ar': 'إرفاق ملف أو صورة'},
  'rec_attach_h': {'en': 'PDF, photo of a paper report, or a scan image.', 'ar': 'ملف PDF أو صورة لتقرير ورقي أو صورة أشعة.'},
  'rec_take_photo': {'en': 'Take a photo', 'ar': 'التقاط صورة'},
  'rec_from_files': {'en': 'Choose a file', 'ar': 'اختيار ملف'},
  'rec_added': {'en': 'Record added', 'ar': 'تمت إضافة السجل'},
  'rec_added_h': {'en': 'Stored on your device. Yours by design.', 'ar': 'محفوظ على جهازك. ملكك بالتصميم.'},
  'pages': {'en': 'pages', 'ar': 'صفحات'},
  'store_manage': {'en': 'Manage storage', 'ar': 'إدارة التخزين'},
  'add_calendar': {'en': 'Add to calendar', 'ar': 'أضف للتقويم'},

  // Storage & sync
  'storage': {'en': 'Storage & sync', 'ar': 'التخزين والمزامنة'},
  'storage_short': {'en': 'Storage', 'ar': 'التخزين'},
  'store_local': {'en': 'On this device', 'ar': 'على هذا الجهاز'},
  'store_icloud': {'en': 'iCloud', 'ar': 'آي كلاود'},
  'store_gdrive': {'en': 'Google Drive', 'ar': 'جوجل درايف'},
  'store_synced': {'en': 'Synced', 'ar': 'تمت المزامنة'},
  'store_local_only': {'en': 'Local only', 'ar': 'محلي فقط'},
  'store_backed': {'en': 'Backed up', 'ar': 'محفوظ احتياطياً'},
  'cancel': {'en': 'Cancel', 'ar': 'إلغاء'},

  // Nearby care / map
  'map_nearby': {'en': 'Nearby care', 'ar': 'رعاية قريبة'},
  'map_search_ph': {'en': 'Search clinics, pharmacies…', 'ar': 'ابحث عن عيادة أو صيدلية…'},
  'map_all': {'en': 'All', 'ar': 'الكل'},
  'map_open_now': {'en': 'Open now', 'ar': 'مفتوح الآن'},
  'map_distance': {'en': 'away', 'ar': 'بُعد'},
  'map_call': {'en': 'Call', 'ar': 'اتصال'},
  'map_directions': {'en': 'Directions', 'ar': 'اتجاهات'},
  'map_list': {'en': 'List', 'ar': 'قائمة'},
  'map_map': {'en': 'Map', 'ar': 'خريطة'},
  'map_found': {'en': 'places nearby', 'ar': 'مكان بالقرب منك'},
  'map_your_loc': {'en': 'Your location', 'ar': 'موقعك'},
  'map_no_results': {'en': 'No places found', 'ar': 'لا توجد أماكن'},
};

/// Translate [key] for [lang], falling back to English then the key itself.
String tr(String key, String lang) =>
    kStrings[key]?[lang] ?? kStrings[key]?['en'] ?? key;
