import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'i18n/messages.i69n.dart';
import 'i18n/messages_ar.i69n.dart';

final translationCatalogProvider = Provider<TranslationCatalog>(
  (_) => const TranslationCatalog(),
);

/// App translations backed by i69n **compile-time** message bundles.
///
/// Bundles are generated by build_runner from `i18n/*.i69n.json`. English is the
/// default bundle; every locale class `extends` it, so a missing key falls back
/// to English automatically, then to the key itself. Lookups go through the
/// generated `[]` operator (dotted-path traversal), so the string-key call sites
/// — `translate('auth.email.title')` — keep working unchanged.
///
/// To add/change copy: edit the JSON and re-run
/// `dart run build_runner build` in `packages/core`.
class TranslationCatalog {
  const TranslationCatalog();

  // One Arabic bundle for now; any `ar-*` locale resolves to it via the
  // language-subtag fallback in [translate].
  static const Map<String, Messages> _bundles = {
    'en': Messages(),
    'ar': Messages_ar(),
  };

  /// Keys renamed at codegen for Dart-identifier safety (reserved words and
  /// leaf-vs-namespace collisions). Call sites still use the original key.
  static const Map<String, String> _alias = {
    'common.continue': 'common.continue_',
    'profile.allergies': 'profile.allergies.label',
  };

  /// Retained for API compatibility. Bundles are compiled in, so this is a
  /// no-op (kept so overriding fakes/callers stay valid).
  Future<void> load(List<String> locales) async {}

  String translate(String key, {String locale = 'en'}) {
    final bundle = _bundles[locale] ?? _bundles[_langOf(locale)] ?? _bundles['en']!;
    try {
      final value = bundle[_alias[key] ?? key];
      return value is String ? value : key;
    } catch (_) {
      return key; // unknown key → graceful fallback to the key itself
    }
  }

  bool hasTranslation(String key, String locale) {
    final bundle = _bundles[locale] ?? _bundles[_langOf(locale)] ?? _bundles['en']!;
    try {
      return bundle[_alias[key] ?? key] is String;
    } catch (_) {
      return false;
    }
  }

  /// Language subtag of a locale (`ar-SA` → `ar`).
  String _langOf(String locale) {
    final i = locale.indexOf('-');
    return i == -1 ? locale : locale.substring(0, i);
  }
}
